In [41]:
import pandas as pd
import os
import numpy as np
from IPython.display import display



# Pfad zum Ordner setzen, der die Textdateien enthält
ordner_pfad = 'C:/Users/erikm/Desktop/Diplomarbeit Erik Marr/Daten/DatenSimulation'  # Ersetzen Sie dies mit dem tatsächlichen Pfad

# Liste, um die DataFrames zu speichern
df_list = pd.DataFrame()

df_x = []
df_y = []
df_t = []


df_x = pd.read_csv("C:/Users/erikm/Desktop/Diplomarbeit Erik Marr/Daten/DatenSimulation/Skalen/TPath_coorX.txt",delimiter='  ', engine='python' )
df_y = pd.read_csv("C:/Users/erikm/Desktop/Diplomarbeit Erik Marr/Daten/DatenSimulation/Skalen/TPath_coorY.txt",delimiter='  ', engine='python' )
df_t = pd.read_csv("C:/Users/erikm/Desktop/Diplomarbeit Erik Marr/Daten/DatenSimulation/Skalen/TPath_time.txt",delimiter='  ', engine='python' )
df_x_list = df_x.iloc[:, 0].tolist()
df_y_list = df_y.iloc[:, 0].tolist()
df_t_list = df_t.iloc[:, 0].tolist()

In [42]:
# Pfad zum Verzeichnis mit den CSV-Dateien

df_all = pd.DataFrame(columns=["x", "y", "t", "F", "I", "Temperatur"])
df_test = pd.DataFrame()

verzeichnis = ordner_pfad

# Durchlaufen aller Dateien im Verzeichnis
for dateiname in os.listdir(verzeichnis):
    if dateiname.endswith('.txt'):
        # Pfad zur aktuellen Textdatei
        voller_pfad = os.path.join(verzeichnis, dateiname)

        # Einlesen der Textdatei in ein temporäres DataFrame
        df_temp = pd.read_csv(voller_pfad, sep='\s+', header=None, index_col=None)

        # Hinzufügen der sechsten Spalte "Temperatur" mit den Werten aus der Textdatei
        df_test = df_temp.values.ravel()
        print(df_test)
        # Fügen Sie df_temp dem gesamten DataFrame df_all hinzu
        #df_all = pd.concat([df_all, df_temp], ignore_index=True)
        
        
#print(df_test)
        
             
        # with open(voller_pfad, 'r') as file:
        #     lines = file.readlines()
        #     for i, line in enumerate(lines):
        #         values = line.strip().split(',')  # Annahme: CSV ist kommasepariert
        #         if len(values) >= 6:
        #             df.at[i, 'Sechste_Spalte'] = values[5]
        #         
        # 
        # df.loc[-1] = df_y_list
        # df.index = df.index + 1
        # df = df.sort_index()
        # 
        # # Transponieren des DataFrame
        # df_transponiert = df.T
        # 
        # # Bestimmen des neuen Dateinamens
        # neuer_dateiname = 'transponiert_' + dateiname
        # neuer_voller_pfad = os.path.join(verzeichnis, neuer_dateiname)
        # 
        # # Speichern des transponierten DataFrame in einer neuen CSV-Datei
        # df_transponiert.to_csv(neuer_voller_pfad, header=False)

print("Transposition aller CSV-Dateien abgeschlossen.")


[3.3092e+02 3.3278e+02 3.3456e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
[3.4413e+02 3.4669e+02 3.4913e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
[2.9815e+02 2.9815e+02 2.9815e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
[2.9824e+02 2.9825e+02 2.9826e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
[2.9874e+02 2.9881e+02 2.9887e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
[3.0000e+02 3.0018e+02 3.0035e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
[3.0212e+02 3.0244e+02 3.0273e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
[3.0473e+02 3.0520e+02 3.0563e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
[3.0843e+02 3.0908e+02 3.0970e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
[3.1366e+02 3.1461e+02 3.1550e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
[3.2099e+02 3.2233e+02 3.2360e+02 ... 7.8886e-31 7.8886e-31 7.8886e-31]
['3.3092E+02,331.01,331.08,331.14,331.18,331.21,331.23,331.23,331.22,331.2,331.16,331.27,331.36,331.44,331.5,331.56,331.59,331.61,331.62,331.62,331.6,331.74,331.87,331.99,332.09,332.17,332.24,332.29,332.33,33

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [15]:

df = pd.read_csv('C:/Users/erikm/Desktop/Diplomarbeit Erik Marr/Daten/DatenSimulation/transponiert_TPath_1_valu.txt', delimiter='  ', engine='python')
print(df)
df.shape

    2.9815E+02,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.15,298.1

(400, 1)